basePath: /
consumes:
- application/json
definitions:
  domain.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      role:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    name: Yousef Support
    url: http://github.com/yousefggg
  description: Микросервис для аутентификации пользователей (регистрация и логин).
  termsOfService: http://swagger.io/terms/
  title: Auth Service API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Проверяет данные и возвращает JWT токен
      parameters:
      - description: Данные для входа (email, password)
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: 'token: JWT_TOKEN_HERE'
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 'error: unauthorized'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Вход
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя в системе
      parameters:
      - description: Данные пользователя (email, password, role)
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "201":
          description: 'message: user created'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 'error: invalid input'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'error: internal server error'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Регистрация
      tags:
      - auth
produces:
- application/json
swagger: "2.0"
